name: deepconvlstm
dataset_name: hawthorne_har
devices: ['cuda:0']
anno_json: [
  'data/hawthorne_har/annotations/0_versus_2_sbj_0.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_1.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_2.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_3.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_4.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_5.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_6.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_7.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_8.json',
  'data/hawthorne_har/annotations/0_versus_2_sbj_9.json'
]
dataset: {
  sens_folder: ./data/hawthorne_har/day,
  input_dim: 3,
  sampling_rate: 12.5,
  include_null: True,
  has_null: True,
  window_size: 13,
  window_overlap: 50,
}
model: {
  conv_kernels: 64,
  conv_kernel_size: 3,
  lstm_units: 1024,
  lstm_layers: 1,
  dropout: 0.5
}
train_cfg: {
  lr: 0.2,
  lr_decay: 0.9,
  lr_step: 250,
  epochs: 1000,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  batch_size: 100,
}